### PR TITLE
Updating VM and using boostrap script, refs #12

### PR DESCRIPTION
**Pull request by awead**
This uses Ubuntu 14 LTS server which should last us a while.  Still a little finicky on the bootup, so please take a look before merging.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
One difference I've noticed so far is that I needed to startup with `vagrant up --provision` to get the new provisioning script to run, though this shouldn't be an issue in environments where sufia-vagrant has never been provisioned before.

**Comment by mjgiarlo** [comment]
Refs #12

**Comment by mjgiarlo** [comment]
OK, the provisioning was humming along just fine, and then:

```
==> default: Installing Sufia
==> default: ruby-2.1.2 - #gemset created /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant
==> default: ruby-2.1.2 - #generating sufia-vagrant wrappers
==> default: ..........
==> default: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
==> default: installing your bundle as root will break this application for all non-root
==> default: users on this machine.
==> default: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
==> default: 
==> default:     /usr/local/rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20140717-7967-5b8blj.rb extconf.rb 
==> default: Cannot allocate memory - /usr/local/rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20140717-7967-5b8blj.rb extconf.rb  2>&1
==> default: 
==> default: Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant/gems/nokogiri-1.6.2.1 for inspection.
==> default: Results logged to /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant/extensions/x86_64-linux/2.1.0/nokogiri-1.6.2.1/gem_make.out
==> default: An error occurred while installing nokogiri (1.6.2.1), and Bundler cannot
==> default: continue.
==> default: Make sure that `gem install nokogiri -v '1.6.2.1'` succeeds before bundling.
==> default: rake aborted!
==> default: Bundler::GemNotFound: Could not find nokogiri-1.6.2.1 in any of the sources
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:92:in `block in materialize'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:85:in `map!'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:85:in `materialize'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:133:in `specs'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:178:in `specs_for'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:167:in `requested_specs'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/environment.rb:18:in `requested_specs'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:13:in `setup'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:120:in `setup'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/setup.rb:17:in `<top (required)>'
==> default: /vagrant/config/boot.rb:4:in `<top (required)>'
==> default: /vagrant/config/application.rb:1:in `<top (required)>'
==> default: /vagrant/Rakefile:4:in `<top (required)>'
==> default: /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant/bin/ruby_executable_hooks:15:in `eval'
==> default: /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant/bin/ruby_executable_hooks:15:in `<main>'
==> default: (See full trace by running task with --trace)
==> default: rake aborted!
==> default: Bundler::GemNotFound: Could not find nokogiri-1.6.2.1 in any of the sources
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:92:in `block in materialize'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:85:in `map!'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:85:in `materialize'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:133:in `specs'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:178:in `specs_for'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/definition.rb:167:in `requested_specs'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/environment.rb:18:in `requested_specs'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/runtime.rb:13:in `setup'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:120:in `setup'
==> default: /usr/local/rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler/setup.rb:17:in `<top (required)>'
==> default: /vagrant/config/boot.rb:4:in `<top (required)>'
==> default: /vagrant/config/application.rb:1:in `<top (required)>'
==> default: /vagrant/Rakefile:4:in `<top (required)>'
==> default: /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant/bin/ruby_executable_hooks:15:in `eval'
==> default: /usr/local/rvm/gems/ruby-2.1.2@sufia-vagrant/bin/ruby_executable_hooks:15:in `<main>'
==> default: (See full trace by running task with --trace)
==> default: Starting Sufia
==> default: /tmp/vagrant-shell: line 48: rails: command not found
==> default: ./script/restart_resque.sh ↠ killing resque-pool
==> default: ./script/restart_resque.sh ↠ starting resque-pool
==> default: bundler: command not found: resque-pool
==> default: Install missing gem executables with `bundle install`
==> default: All done!
```

**Comment by tpendragon** [comment]
Can I recommend putting the script somewhere less root-y? I've heard of (and like the idea of) bin/setup

**Comment by awead** [comment]
@terrellt You mean put the Sufia install bits in it's own script at /vagrant/bin/setup ?  The bootstrap script is run as root or as the vagrant user?

@mjgiarlo The problem with using the --provision option is that re-runs the entire script. Perhaps we should build in some logic to bypass those steps if they've already been done.

**Comment by mjgiarlo** [comment]
@awead Good point -- the current provisioning script does combine steps that need to be done only on setup and steps that need to be done every time the VM is booted up (start rails, start resque, etc.).  If we can disentangle those, that'd be ideal.

**Comment by tpendragon** [comment]
@awead https://github.com/OregonDigital/oregondigital/blob/feature/SpeedupLoad/bin/setup may be helpful.

**Comment by awead** [comment]
So that's essentially doing everything provisioning is doing.  Assuming that Vagrant's provisioning process would call the setup script, is there a reason for the separation?  Each seems to be doing the same thing.  It doesn't matter to me, I'm just curious.

**Comment by tpendragon** [comment]
> So that's essentially doing everything provisioning is doing. Assuming that Vagrant's provisioning process would call the setup script, is there a reason for the separation? Each seems to be doing the same thing. It doesn't matter to me, I'm just curious.

There's no separation in that one, it's just checking and only installing RVM if it doesn't exist. The vagrant file has an option to :run => always

**Comment by jeremyf** [comment]
Ping @awead

**Comment by awead** [comment]
@jeremyf Haven't used this in months. It might no longer be an issue, AFAIK.

**Comment by jeremyf** [comment]
@awead would you like this merged? Or closed?

**Pull request closed without merging**
